# Generated by Django 5.2.4 on 2025-07-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_budget_created_at_alter_budget_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
